- name: 'install db service'
  apt:
    update_cache: true
    name: '{{ mariadb_pkgs }}'

- name: 'render db scripts'
  template:
    src: '{{ item }}'
    dest: '/tmp/{{ dest_item }}'
  loop: '{{ scripts }}'
  loop_control:
    label: '{{ item }}'
  vars:
    dest_item: '{{ item.split(".")[:-1] | join(".") }}'

- name: 'run db scripts'
  shell: 'mariadb < /tmp/{{ item }}'
  loop: '{{ scripts }}'

- name: 'remove db scripts'
  file:
    path: '/tmp/{{ item }}'
    state: absent
  loop: '{{ scripts }}'