- name: 'recreate {{ web_dir }}'
  file:
    path: '{{ web_dir }}'
    state: '{{ item }}'
  loop: ['absent', 'directory']

- name: 'ensure correct {{ web_dir }} ownership'
  file:
    path: '{{ web_dir }}'
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: 'install wp-cli'
  get_url:
    url: "{{ wpcli_url }}"
    dest: "{{ wpcli_install_dir }}/wp"
    group: ubuntu
    owner: ubuntu
    mode: +x

- name: 'install wordpress'
  shell: 'wp {{ item.cmd_arg }}'
  become: false
  loop: '{{ wordpress_install_commands }}'
  loop_control:
    label: '{{ item.name }}'
  args:
    chdir: '{{ web_dir }}'

- name: 'ensure correct permissions'
  file:
    state: '{{ item.type | default("directory") }}'
    path: '{{ web_dir }}/{{ item.dir }}'
    mode: '{{ item.mode }}'
    owner: '{{ item.owner | default(omit) }}'
    group: '{{ item.owner | default(omit) }}'
  loop: '{{ wordpress_permissions }}'
  loop_control:
    label: '{{ item.dir }}'

- name: 'update blog details'
  shell: 'wp {{ item.cmd_arg }}'
  become: false
  loop: '{{ wordpress_blog }}'
  loop_control:
    label: '{{ item.name }}'
  args:
    chdir: '{{ web_dir }}'

- name: 'update home title'
  template:
    src: 'home_template.html.j2'
    dest: '{{ wp_home_template_path }}'