node_index: '{{ inventory_hostname.split("-")[-2] }}'

wp_home_page_title: Namespaces
wp_home_template_path: '{{ web_dir }}/wp-content/themes/twentytwentythree/templates/home.html'

wp_blog_file: linux_namespaces.txt
wp_blog_title: '{{ (wp_blog_file.split("_") | join(" ") | title)[:-4] }}'
wp_blog_text: '{{ lookup("file", (playbook_dir + "/../content/" + wp_blog_file)) }}'

wpcli_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
wpcli_install_dir: '/usr/local/bin'

# Wordpress credentials and values are directly fetched;
# from extra vars and are all available inside the config/vars_config.yml file;
wordpress_install_commands: [
  {
    name: 'download wordpress',
    cmd_arg: "core download"
  },
  {
    name: 'create wp-config.php',
    cmd_arg: "config create --dbname={{ wp_db_name }} --dbuser={{ wp_db_user }}-{{ node_index }} --dbpass={{ wp_db_passwd }} --dbhost={{ db_instance_address }} --dbprefix=tux{{ node_index }}_"
  },
  {
    name: 'install wordpress',
    cmd_arg: "core multisite-install --url={{ web_hostname }} --title='{{ wp_web_title }}' --admin_user={{ wp_admin_user }} --admin_password={{ wp_admin_passwd }} --admin_email={{ wp_admin_email }}"
  }
]

wordpress_blog: [
  {
    name: 'delete default blog',
    cmd_arg: "post delete 1"
  },
  {
    name: 'create blog',
    cmd_arg: "post create --post_type=post --post_title='{{ wp_blog_title }}' --post_content='{{ wp_blog_text }}' --post_status=publish"
  }
]

wordpress_permissions: [
  {dir: 'wp-admin', mode: '0755'},
  {dir: 'wp-includes', mode: '0755'},
  {dir: 'wp-content', mode: '0755'},
  {dir: 'wp-content/themes', mode: '0755'},
  {dir: 'wp-content/plugins', mode: '0755'},
  {dir: 'wp-content/uploads', mode: '0755'},
  {dir: 'index.php', mode: '0644', type: 'file'},
  {dir: 'wp-config.php', owner: 'www-data', mode: '0644', type: 'file'}
]
