- name: 'Deploying Wordpress'
  hosts: all
  become: true
  vars_files: vars.yml
  vars:
    ansible_user: ubuntu


  tasks:
  - name: Install apache2/php components
    include_role:
      name: php
    when: ('web_servers' in group_names)

  - name: Install database components
    include_role:
      name: mariadb
    when: ('db' in group_names)

  - name: check if vm restarts are necessary..
    meta: flush_handlers

  - name: Install wordpress components
    include_role:
      name: wordpress
    when: ('web_servers' in group_names)

  - name: Set up tables optimization schedule
    import_tasks: tasks/optimize_tables.yml
    when: ('db' in group_names)